config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'toppages#show'
  resources :users, only: [:index, :show]
  resources :messages, only: [:create]
  resources :rooms, only: [:create, :show]
  resources :relationships, only: [:create, :destroy, :show, :edit]
  resources :communities, only: [:new, :create, :index]
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/community.rb
class Community < ApplicationRecord
  has_many :user
  
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy 
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :district])
  end

end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      redirect_to :root
    else 
      redirect_to action:'new'
    end
  end

  def index
    @rankings =  Community.group(:district).pluck(:district).map{|district|
      [district,
      Community.where(district: district).group(:ancestry).order(:ancestry).count(:ancestry),
      Community.where(district: district).group(:volunter).order(:volunter).count(:volunter),
      ]}
    
  end


  private
  def community_params
    params.require(:community).permit(:ancestry, :volunter, :district).merge(user_id: current_user.id)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  

  def index
    @message = Message.new
    @messages = Message.includes(:user)
  end

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
  end



end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


  def show
    user = User.find(params[:id])
    @messages = Message.all
  end

  def follow
    current_user.follow(params[:id])
    redirect_to root_path
  end

  def unfollow
    current_user.unfollow(params[:id])
    redirect_to root_path
  end

  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def show
    @user = User.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

end

app/views/communities/index.html.erb
<div class="community">
  <h1 class="community--title">23区の不足している物資とボランティアの有無情報</h1><br/>
   <% @rankings.each do |r| %>
    <% district,ancestry,volunter = [r[0],r[1].keys,r[2].keys] %>
    <p class="rankings--result" border:bule solid 1px;><%= district %><br>不足している物資<br><%= ancestry[0..2].join(",") %><br>ボランティア<%= volunter.first %></p><br/><br/>
  <% end %>
</div>


 

app/views/communities/new.html.erb
<div class="community">
  <h1 class="community--title">各項目を選択して送信してください</h1>
<% @community = Community.new unless @community %>
<%= form_for @community do |f| %>
  <div class="filed--district">
    <%= f.label :区を選択してください %> <br />
    <%= f.select :district, 
    [["足立区","足立区"],
     ["荒川区","荒川区"],
     ["板橋区","板橋区"],
     ["江戸川区","江戸川区"],
     ["大田区","大田区"],
     ["葛飾区","葛飾区"],
     ["北区","北区"],
     ["江東区","江東区"],
     ["品川区","品川区"],
     ["渋谷区","渋谷区"],
     ["新宿区","新宿区"],
     ["杉並区","杉並区"],
     ["墨田区","墨田区"],
     ["世田谷区","世田谷区"],
     ["台東区","台東区"],
     ["千代田区","千代田区"],
     ["中央区","中央区"],
     ["豊島区","豊島区"],
     ["中野区","中野区"],
     ["練馬区","練馬区"],
     ["文京区","文京区"],
     ["港区","港区"],
     ["目黒区","目黒区"],]%>
  </div>
  <div class="filed--ancestry">
    <%= f.label :不足している資源を選択してください %> <br />
    <%= f.select :ancestry, 
    [["水","水"],
     ["米やパン","米やパン"],
     ["おかず","おかず"],
     ["日用品","日用品"],
     ["電気や電池","電気や電池"],
     ["毛布","毛布"],
     ["タオル","タオル"],
     ["衣類","衣類"],
     ["下着","下着"],] %>
  </div>
  <div class="filed--volunter">
  <%= f.label :ボランティアの有無を選択してください %><br/>
  <%= f.select :volunter,
    [["必要だと思う","必要だと思う"],
     ["必要でない","必要でない"],] %>
  </div>
  <%= f.submit "登録", class:"community--button" %>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommunityReprot</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <div class="header__title">
        <%= link_to "CommunityReport", root_path, class: "header__title--text" %>
        <% if user_signed_in? %>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header__title--session" %>
          <%= link_to "#{current_user.nickname}さん", user_path(current_user.id), class: "header__title--session" %>
        <% else %>
          <%= link_to "新規登録", new_user_registration_path, class: "header__title--session" %>
          <%= link_to "ログイン", new_user_session_path, class: "header__title--session" %> 
        <% end %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.email %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/toppages/_left-middle.html.erb
<div class="content__left">
  <div class="content__left__friends">
    <div class="content__left__friends--list">
      <% User.all.where.not(id: current_user.id).each do |user| %>
          <p><%= user.nickname %></p>
      <% end %>
    </div>
  </div>
</div>

app/views/toppages/_right-middle.html.erb
<div class="content__right">
  <div class="content__right__groups">
    
    <div class="content__right__groups--list">
    </div>
  </div>
</div>

app/views/toppages/show.html.erb
<div class="content">
  <div class="image--content">
    <div class="image--content__title">
      <h1>community reprotへようこそ</h1>
      <p>community reprotは安否確認サービスです。</p>
      <p>皆様の健康と安全をサポートします。</p>
      <small>※※※安否の送信（位置情報）は開発中となります。※※※</small>
      <br/>
      <br/>
      <br/>
      <br/>
    </div>
    <div class="image--content__select"> 
      <% if user_signed_in? %>
        <%= link_to 'チャットへ',users_path(@user), class: "follow"%>
        <%= link_to '23区を確認', communities_path, class: "reprot-index"%>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <br/>
        <%= link_to '安否を送信', "#", class: "safety"%>
        <%= link_to '区の現状を送信', new_community_path, class: "reprot"%>
      <% else %>
        <p>新規登録またはログインをお願いします</p>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="users">
  <p><%= link_to "マイページへ", user_path(current_user) %></p>
  <h2>ユーザー一覧画面</h2>
  <% User.all.where.not(id: current_user.id).each do |user| %>
    <p>
      <%= "id: #{user.id} email: #{user.email}" %>
      <% if current_user.following?(user) %>
        <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
      <% else %>
        <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
      <% end %>
  <% end %>
</div>

<h2>チャットを送るユーザーを選択してください</h2>
  <% @users.each do |u| %>
  <p><a href="/users/<%= u.id %>"><%= u.nickname %>さん</a></p>
  <hr>
  <% end %>

app/views/users/show.html.erb
<div class="users"> 
  <p><%= "ニックネーム: #{@user.nickname}" %></p>
  <p><%= "email: #{@user.email}" %></p>
  <p><%= "フォロー数: #{@user.follower.count}" %></p>
  <p><%= "フォロワー数: #{@user.followed.count}" %></p>
  <% unless @user == current_user %>
    <% if current_user.following?(@user) %>
      <%= link_to 'フォロー外す', unfollow_path(@user.id), method: :POST %>
    <% else %>
      <%= link_to 'フォローする', follow_path(@user.id), method: :POST %>
    <% end %>
  <% end %>
  <p></p>
  
  <h3>フォロー一覧</h3>
    <% @user.following_user.where.not(id: current_user.id).each do |user| %>
      <p>
        <%= "id: #{user.id} email: #{user.email}" %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
        <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
        <% end %>
        <%= link_to "show", user_path(user) %>
      </p>
    <% end %>
  <h3>フォロワー一覧</h3>
    <% @user.follower_user.where.not(id: current_user.id).each do |user| %>
      <p>
        <%= "id: #{user.id} email: #{user.email}" %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', unfollow_path(user.id), method: :POST %>
        <% else %>
          <%= link_to 'フォローする', follow_path(user.id), method: :POST %>
        <% end %>
        <%= link_to "show", user_path(user) %>
      </p>
    <% end %>
</div>
<div class= "users">
<% if @user.id == current_user.id %>
<% else %>
  <% if @isRoom == true %>
    <p><a href="/rooms/<%= @roomId %>">チャットへ</a>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "チャットを始める" %>
    <% end %>
  <% end %>
<% end %>
</div>